merging

diff --git a/ROMFS/px4fmu_common/init.d/rcS b/ROMFS/px4fmu_common/init.d/rcS
--- a/ROMFS/px4fmu_common/init.d/rcS
+++ b/ROMFS/px4fmu_common/init.d/rcS
@@ -93,14 +93,6 @@ then
 		fi
 	fi
 
-	# Check for an update of the ext_autostart folder, and replace the old one with it
-	if [ -e /fs/microsd/ext_autostart_new ]
-	then
-		echo "Updating external autostart files"
-		rm -r $SDCARD_EXT_PATH
-		mv /fs/microsd/ext_autostart_new $SDCARD_EXT_PATH
-	fi
-
 	set PARAM_FILE /fs/microsd/params
 	set PARAM_BACKUP_FILE "/fs/microsd/parameters_backup.bson"
 fi
@@ -170,7 +162,7 @@ else
 		param select-backup $PARAM_BACKUP_FILE
 	fi
 
-	if ver hwcmp PX4_FMU_V5X PX4_FMU_V6X ARK_FMU_V6X PX4_FMU_V6XRT
+	if ver hwcmp PX4_FMU_V5X PX4_FMU_V6X ARK_FMU_V6X
 	then
 		netman update -i eth0
 	fi
@@ -274,9 +266,12 @@ else
 		. $FCONFIG
 	fi
 
-	if px4io supported
+	#
+	# Start IO for PWM output or RC input if enabled
+	#
+	if param compare -s SYS_USE_IO 1
 	then
-	# Check if PX4IO present and update firmware if needed.
+		# Check if PX4IO present and update firmware if needed.
 		if [ -f $IOFW ]
 		then
 			if ! px4io checkcrc ${IOFW}
@@ -298,12 +293,12 @@ else
 					tune_control stop
 				fi
 			fi
+		fi
 
-			if ! px4io start
-			then
-				echo "PX4IO start failed"
-				set STARTUP_TUNE 2 # tune 2 = ERROR_TUNE
-			fi
+		if ! px4io start
+		then
+			echo "PX4IO start failed"
+			set STARTUP_TUNE 2 # tune 2 = ERROR_TUNE
 		fi
 	fi
 
@@ -533,10 +528,6 @@ else
 		then
 			cyphal start
 		fi
-	fi
-	if param greater -s ZENOH_ENABLE 0
-	then
-		zenoh start
 	fi
 
 #
